steps:
  # Maven 빌드를 수행하는 단계
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['package']
    # pom.xml이 있는 하위 디렉터리 지정
    dir: 'server/my-gae-app'

  # 빌드된 애플리케이션을 배포하는 단계 (예시)
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['appengine:deploy', '-Dapp.deploy.projectId=CheckPlusManagement']
    # pom.xml이 있는 하위 디렉터리 지정
    dir: 'server/my-gae-app'
#  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#    args: ['gcloud', 'app', 'deploy']
#  - name: 'gcr.io/cloud-builders/gcloud'
#    args: ['app', 'deploy', '--project', 'CheckPlusManagement', '--logging=CLOUD_LOGGING_ONLY', '--no-promote']
    # 배포 파일이 있는 하위 디렉터리 지정
    dir: 'server/my-gae-app'
options:
  logging: CLOUD_LOGGING_ONLY # 이 부분을 추가합니다